### ISSUE TITLE
output structure?

### ISSUE THREAD

**Issue by antithing** [simbaforrest/masfm#1]
Hi, and thank you for making this code available.  I am running it on the input file that is provided, and am a bit confused about the output.  I would expect the corners, or position and rotation of markers, but it looks like:

```
19
Tag36h11.14 2.08100705561662e-05 5.52231728418008e-06 -2.5539668484284e-05 0.000176555558609455 -0.000189604698513551 1.49357654697979e-05
0.0001 0 0 0 0 0
0 0.0001 0 0 0 0
0 0 0.0001 0 0 0
0 0 0 0.01 0 0
0 0 0 0 0.01 0
0 0 0 0 0 0.01
	9 0 2 9 11 105 120 123 152 154
Tag36h11.3 2.45134053225531 0.416518411807496 0.999966806243172 -607.649138811526 1040.90632069732 2995.01405724277
1 0 0 0 0 0
0 1 0 0 0 0
0 0 1 0 0 0
0 0 0 1 0 0
0 0 0 0 1 0
0 0 0 0 0 1
	14 1 4 10 12 15 19 21 102 106 111 137 141 143 145
Tag36h11.0 2.4786236483332 -0.185234703531859 -0.162509253011588 1722.59336852785 323.924272329527 1570.51426109844
1 0 0 0 0 0
0 1 0 0 0 0
0 0 1 0 0 0
0 0 0 1 0 0
0 0 0 0 1 0
0 0 0 0 0 1
	18 3 5 7 8 14 17 35 37 67 69 96 101 103 113 115 121 135 138
Tag36h11.4 -2.19822377776214 2.06905413334706 0.00137033032088581 318.619216698044 -1470.545404413 2944.84767918785
1 0 0 0 0 0
0 1 0 0 0 0
0 0 1 0 0 0
0 0 0 1 0 0
0 0 0 0 1 0
0 0 0 0 0 1
	8 6 23 72 74 104 112 114 139
```

Could you explain this for me please if you have a moment? 

I am also testing a live camera, I see markers detected, but 'views' stays at 0. Do I need to capture the frames somehow? Or is it automatic? Is it possible to return the marker ids and corners?

Thanks again!

**Comment by simbaforrest** [comment]
Hi, thanks for your interests in the code.

For the output format, you can check this function: https://github.com/simbaforrest/masfm/blob/master/source/cmgraph.cpp#L191-L226

Basically, the rotations are encoded by angle-axis form instead of rotation matrix. The covariance matrix estimations are also outputed per marker.

After all marker states are outputed, the function will output view/camera states.

See my comments with # below:
```
#number of markers in the camera-marker graph
19
#the first marker's name, angle-axis representation of rotation (the first 3 numbers), and locations (the last 3 numbers)
Tag36h11.14 2.08100705561662e-05 5.52231728418008e-06 -2.5539668484284e-05 0.000176555558609455 -0.000189604698513551 1.49357654697979e-05
#the covariance estimation of the first marker's pose, a 6x6 matrix, for the first marker, this is always the same as the input
0.0001 0 0 0 0 0
0 0.0001 0 0 0 0
0 0 0.0001 0 0 0
0 0 0 0.01 0 0
0 0 0 0 0.01 0
0 0 0 0 0 0.01    
#9views/cameras observed this marker, and their ids (0 2 9 11 105 120 123 152 154).
9 0 2 9 11 105 120 123 152 154
```

For live camera-marker graph estimation with webcam, you may find the keyboard commands in this function:
https://github.com/simbaforrest/masfm/blob/58e93d560e3b20e01fc87b3926aa87578f6d7421/source/masfm.cpp#L352-L377
which is invoked here:
https://github.com/simbaforrest/masfm/blob/master/source/masfm.cpp#L352-L377

Hope this helps!

**Comment by antithing** [comment]
Hi, and Thanks! So just to be clear, in live mode, I just need to move the camera, and it should capture the views? It seems to show the markers, but the view count stays at zero.
Should it capture every frame? Or just when a certain number of markers are found? 
Thanks again!

**Comment by simbaforrest** [comment]
Hi, in live mode, you need to press key 'l' to log the current view so it will save the markers detected in the current view in the camera-marker graph for reconstruction and pose estimation. Thus, the current view should contain at least one detected marker (>2 is always recommended). Once you observed more than 2 markers in a same view, you can press key 'o' to call cmgraph to optimize the graph and plot 3d coordinate frame for each marker.
Right now the code in the live mode, I didn't output the final optimized graph of markers and views, you can easily do that by invoking the graph.report function in the following lines:
https://github.com/simbaforrest/masfm/blob/58e93d560e3b20e01fc87b3926aa87578f6d7421/source/masfm.cpp#L334-L344
Example of invoking that can be found in the batch mode:
https://github.com/simbaforrest/masfm/blob/58e93d560e3b20e01fc87b3926aa87578f6d7421/source/masfm.cpp#L84-L96

**Comment by antithing** [comment]
Thank you! I have everything running with my camera, but when I try to add a view, i get:

`no connection to the graph, ignored`

here:

https://github.com/simbaforrest/masfm/blob/58e93d560e3b20e01fc87b3926aa87578f6d7421/source/masfm.cpp#L247

The markers are displayed. What could be wrong?

Thank you again for your help and time.

**Comment by antithing** [comment]
Aha! I was not loading the ini properly. Everything seems to be up and running now. Thank you again for your code, and your time. Much appreciated! Have a great weekend.

**Comment by antithing** [comment]
Sorry to keep bugging you, one more question... I have it running, and returning the mapped data. The results look pretty good, but the position values are incorrect, putting the mapped markers too far apart. i have set the marker_half_size to half the edge of my markers, but it still looks wrong. i am streaming data in from my camera and have adjusted the code a little, using the following function and passing each frame to it as a Mat. If you have time, could you take a look and let me know if I am missing anything? Thank you again!

```
	void RunOneFrame(cv::Mat frame, int num)
	{
		load_calibration(G);
		static helper::PerformanceMeasurer PM;
		std::vector<TagDetection> detections;
		cv::Mat orgFrame;
		frame.copyTo(orgFrame);
		PM.tic();
		gDetector->process(frame, detections);
		logld("[TagDetector] process time = " << PM.toc() << " sec.");

		//visualization
		int nValidDetections = 0;
		logld(">>> find: ");
		for (int i = 0; i<(int)detections.size(); ++i) {
			TagDetection &dd = detections[i];
			if (dd.hammingDistance>this->hammingThresh) continue;
			++nValidDetections;

			logld("id=" << dd.id << ", hdist=" << dd.hammingDistance << ", rotation=" << dd.rotation);
			cv::putText(frame, dd.toString(), cv::Point(static_cast<int>(dd.cxy[0]), static_cast<int>(dd.cxy[1])),
				CV_FONT_NORMAL, tagTextScale, helper::CV_BLUE, tagTextThickness);
			cv::Mat Homo = cv::Mat(3, 3, CV_64FC1, dd.homography[0]);
			helper::drawHomography(frame, Homo);
			cv::circle(frame, cv::Point2d(dd.p[0][0], dd.p[0][1]), 3, helper::CV_GREEN, 2);
		}
		
		//logging results
		if (nValidDetections > 1 && num % 5 == 0) //every 5  frame
		{
			addDetections2CMGraph(detections);

			cmg::Node newView;
			if (optimizeThisView(detections, newView)) {
				plot3dOnFrame(frame, newView);
			}
		}
		
		 if (num % 100 == 0) //save every 100
		 {
			 std::cout << "GRAPH SAVED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! " << num << std::endl;
			 save_graph_states(G);
		}

		cv::putText(frame,
			cv::format("#markers=%-4d #views=%-4d #edges=%-5d",
				G.markers.size(), G.views.size(), G.edges.size()),
			cv::Point(5, 15), CV_FONT_NORMAL, 0.4, helper::CV_BLUE);
				
	
	}

```

**Comment by antithing** [comment]
Aha, of course, i just needed to use `processor(frame);` to call the operator. Thanks again for the code! :)
